name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:

  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install

      - name: Notify Discord on Failure
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"CI pipeline failed! Commit: ${{ github.sha }} by ${{ github.actor }}. Message: ${{ github.event.head_commit.message }}\"}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
  
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.70.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          DEFAULT_BUMP: patch
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}

      - name: Notify Discord on Success
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"Deployment succeeded! New version deployed.\"}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
